rx_pin = 1
tx_pin = 0

[[sensors]]
type = 48323
channel = 3
thing_name = "OutsideWeatherSensor"
thing_endpoint = "ecc040502376.iot.eu-west-1.amazonaws.com"
thing_region = "eu-west-1"

[[sensors]]
type = 52419
channel = 2
thing_name = "IndoorTemperatureSensor"
thing_endpoint = "bc440501476.iot.eu-west-1.amazonaws.com"
thing_region = "eu-west-1"
